/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import ctrl.CategoriaCtrl;
import ctrl.MarcaCtrl;
import ctrl.UnidadeMedCtrl;
import ctrl.DocumentJTextFIXACtrl;
import dao.CategoriaDao;
import dao.MarcaDao;
import dao.UnidadeDao;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Douglas
 */
public class GerirParametros extends javax.swing.JFrame {
    public MarcaDao mDao = new MarcaDao();
    public MarcaCtrl mCtrl = new MarcaCtrl();
    public CategoriaDao cDao = new CategoriaDao();
    public CategoriaCtrl cCtrl = new CategoriaCtrl();
    public UnidadeDao umDao = new UnidadeDao();
    public UnidadeMedCtrl umCtrl = new UnidadeMedCtrl();
    public boolean isEditParam = false;
    public DefaultTableModel objTM;
    /**
     * Creates new form GerirParametros
     */
    public GerirParametros() {
        initComponents();
        
        objTM = (DefaultTableModel) jTableParam.getModel();
        objTM.setRowCount(0);
        System.out.println("codParametro select: "+SisPrinc.codParametro);
        switch(SisPrinc.codParametro){
            case 1: 
                jlTitulo.setText("Controle de Marcas");
                jtNome.setEnabled(true);
                jtNome.setEditable(true);
                jtaDescri.setEnabled(true);
                jtaDescri.setEditable(true);
                
                objTM.addColumn("ID");
                objTM.addColumn("Nome");
                objTM.addColumn("Descrição");
                
                jTableParam.getColumnModel().getColumn(0).setMinWidth(30);
                jTableParam.getColumnModel().getColumn(0).setMaxWidth(30);
                
                jTableParam.getColumnModel().getColumn(1).setMinWidth(90);
                jTableParam.getColumnModel().getColumn(1).setMaxWidth(90);
                
                
            break;
            case 2: 
                jlTitulo.setText("Controle de Categorias");
                jtNome.setEnabled(true);
                jtNome.setEditable(true);
                jtaDescri.setEnabled(true);
                jtaDescri.setEditable(true);
                
                objTM.addColumn("ID");
                objTM.addColumn("Nome");
                objTM.addColumn("Descrição");
                
                jTableParam.getColumnModel().getColumn(0).setMinWidth(30);
                jTableParam.getColumnModel().getColumn(0).setMaxWidth(30);
                
                jTableParam.getColumnModel().getColumn(1).setMinWidth(110);
                jTableParam.getColumnModel().getColumn(1).setMaxWidth(110);
            break;
            case 3: 
                jlTitulo.setText("Controle de Unidade de Medidas");
                jtAbrev.setEnabled(true);
                jtAbrev.setEditable(true);
                jtNome.setEnabled(true);
                jtNome.setEditable(true);
                
                objTM.addColumn("ID");
                objTM.addColumn("Abreviação");
                objTM.addColumn("Descrição");
                
                jTableParam.getColumnModel().getColumn(0).setMinWidth(30);
                jTableParam.getColumnModel().getColumn(0).setMaxWidth(30);
                
                jTableParam.getColumnModel().getColumn(1).setMinWidth(50);
                jTableParam.getColumnModel().getColumn(1).setMaxWidth(50);
            break;
            default : JOptionPane.showMessageDialog(null, "Valor de Parametro não encontrado!!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtAbrev = new javax.swing.JTextField();
        jtNome = new javax.swing.JTextField();
        jlTitulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescri = new javax.swing.JTextArea();
        jbSalvar = new javax.swing.JButton();
        jbExcel = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtPesqParam = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableParam = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Parametros");
        setLocation(((SisPrinc.WIDTH/2)-(getSize().width/2)),((SisPrinc.HEIGHT/2)-(getSize().height/2)));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Abrev.:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jtAbrev.setEditable(false);
        jtAbrev.setDocument(new DocumentJTextFIXACtrl());
        jtAbrev.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtAbrev.setToolTipText("Abreviatura do nome");
        jtAbrev.setEnabled(false);
        jtAbrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAbrevActionPerformed(evt);
            }
        });
        jtAbrev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtAbrevKeyPressed(evt);
            }
        });

        jtNome.setEditable(false);
        jtNome.setDocument(new DocumentJTextFIXACtrl());
        jtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtNome.setToolTipText("Nome do item");
        jtNome.setEnabled(false);
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jlTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("UNIDADE DE MEDIDA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Descrição: ");

        jtaDescri.setEditable(false);
        jtaDescri.setColumns(20);
        jtaDescri.setDocument(new DocumentJTextFIXACtrl());
        jtaDescri.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaDescri.setLineWrap(true);
        jtaDescri.setRows(5);
        jtaDescri.setEnabled(false);
        jScrollPane1.setViewportView(jtaDescri);

        jbSalvar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbExcel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbExcel.setText("Excel");

        jbCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtAbrev))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtNome))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jbExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jbCancel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jtAbrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExcel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jbCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("CADASTRO", jPanel1);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Pesquisar:");

        jtPesqParam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtPesqParam.setToolTipText("Abreviatura do nome");
        jtPesqParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesqParamActionPerformed(evt);
            }
        });
        jtPesqParam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPesqParamKeyPressed(evt);
            }
        });

        jTableParam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableParam);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Pesq");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtPesqParam, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton5)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtPesqParam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("CONSULTA", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtAbrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAbrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAbrevActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        switch(SisPrinc.codParametro){
            case 1:     
                if(!isEditParam){
                    try {
                        if(!mDao.selectMarca(jtNome.getText()).first()){
                            mCtrl.setID(0);
                            mCtrl.setNome(jtNome.getText());
                            mCtrl.setDescri(jtaDescri.getText());

                            mDao.inserir(mCtrl);
                            JOptionPane.showMessageDialog(null, "Marca Salva com sucesso!!!");

                            jtNome.setText("");
                            jtAbrev.setText("");
                            jtaDescri.setText("");
                            
                            jtaDescri.setNextFocusableComponent(jtNome);
                            jtaDescri.nextFocus();

                        }else JOptionPane.showMessageDialog(null, "Marca já existente!!!");
                    } catch (SQLException ex) {
                        Logger.getLogger(GerirParametros.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    
                    mCtrl.setNome(jtNome.getText());
                    mCtrl.setDescri(jtaDescri.getText());
                    if(mDao.alterar(mCtrl)){
                        JOptionPane.showMessageDialog(null, "Marca Alterada com sucesso!!!");
                        isEditParam = false;
                        jtNome.setText("");
                        jtAbrev.setText("");
                        jtaDescri.setText("");
                    }
                }
            break;
            case 2:      
                if(!isEditParam){
                    try {
                        if(!cDao.selecionarCatego(jtNome.getText()).first()){
                            cCtrl.setID(0);
                            cCtrl.setNome(jtNome.getText());
                            cCtrl.setDescri(jtaDescri.getText());

                            cDao.inserir(cCtrl);
                            JOptionPane.showMessageDialog(null, "Categoria Salva com sucesso!!!");

                            jtNome.setText("");
                            jtAbrev.setText("");
                            jtaDescri.setText("");  
                            
                            jtaDescri.setNextFocusableComponent(jtNome);
                            jtaDescri.nextFocus();  
                        }else JOptionPane.showMessageDialog(null, "Categoria já existente!!!");
                    } catch (SQLException ex) {
                        Logger.getLogger(GerirParametros.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    cCtrl.setNome(jtNome.getText());
                    cCtrl.setDescri(jtaDescri.getText());
                    if(cDao.alterar(cCtrl)){
                        JOptionPane.showMessageDialog(null, "Categoria Alterada com sucesso!!!");
                        isEditParam = false;
                        jtNome.setText("");
                        jtAbrev.setText("");
                        jtaDescri.setText("");
                    }
                }
                
            break;
            case 3:      
                if(!isEditParam){
                    try {
                        if(!umDao.selecionarUndMed(jtNome.getText()).first()){
                    
                            umCtrl.setID(0);
                            umCtrl.setAbrev(jtAbrev.getText());
                            umCtrl.setNome(jtNome.getText());

                            umDao.inserir(umCtrl);
                            JOptionPane.showMessageDialog(null, "Unidade de Medida Salva com sucesso!!!");

                            jtNome.setText("");
                            jtAbrev.setText("");
                            jtaDescri.setText("");
                            
                            jtaDescri.setNextFocusableComponent(jtAbrev);
                            jtaDescri.nextFocus();
                        }else JOptionPane.showMessageDialog(null, "Unidade de Medida já existente!!!");
                    } catch (SQLException ex) {
                        Logger.getLogger(GerirParametros.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    umCtrl.setAbrev(jtAbrev.getText());
                    umCtrl.setNome(jtNome.getText());
                    if(umDao.alterar(umCtrl)){
                        JOptionPane.showMessageDialog(null, "Unidade de Medida Alterada com sucesso!!!");
                        isEditParam = false;
                        jtNome.setText("");
                        jtAbrev.setText("");
                        jtaDescri.setText("");
                    } 
                }
                
            break;
            default : JOptionPane.showMessageDialog(null, "Valor de Parametro não encontrado!!!");
        }
        
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jTableParam.getSelectedRow() != -1){
            isEditParam = true;
            switch(SisPrinc.codParametro){
                case 1:
                    mCtrl.setID(Integer.parseInt(objTM.getValueAt(jTableParam.getSelectedRow(), 0).toString()));
                    mCtrl.setNome(objTM.getValueAt(jTableParam.getSelectedRow(), 1).toString());
                    mCtrl.setDescri(objTM.getValueAt(jTableParam.getSelectedRow(), 2).toString());
                    
                    jtNome.setText(mCtrl.getNome());
                    jtaDescri.setText(mCtrl.getDescri());
                    jtAbrev.setNextFocusableComponent(jtNome);
                    jtAbrev.nextFocus();
                    jtNome.selectAll();
                break;
                case 2:
                    cCtrl.setID(Integer.parseInt(objTM.getValueAt(jTableParam.getSelectedRow(), 0).toString()));
                    cCtrl.setNome(objTM.getValueAt(jTableParam.getSelectedRow(), 1).toString());
                    cCtrl.setDescri(objTM.getValueAt(jTableParam.getSelectedRow(), 2).toString());
                    
                    jtNome.setText(cCtrl.getNome());
                    jtaDescri.setText(cCtrl.getDescri());
                    jtAbrev.setNextFocusableComponent(jtNome);
                    jtAbrev.nextFocus();
                    jtNome.selectAll();
                break;
                case 3:
                    umCtrl.setID(Integer.parseInt(objTM.getValueAt(jTableParam.getSelectedRow(), 0).toString()));
                    umCtrl.setAbrev(objTM.getValueAt(jTableParam.getSelectedRow(), 1).toString());
                    umCtrl.setNome(objTM.getValueAt(jTableParam.getSelectedRow(), 2).toString());
                    
                    jtAbrev.setText(umCtrl.getAbrev());
                    jtNome.setText(umCtrl.getNome());
                    jtPesqParam.setNextFocusableComponent(jtAbrev);
                    jtPesqParam.nextFocus();
                    jtAbrev.selectAll();
                break;
            }

            jTabbedPane1.setSelectedIndex(0);
        }else JOptionPane.showMessageDialog(null, "Selecione um item para EDITAR!!!");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtPesqParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesqParamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPesqParamActionPerformed

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        selectParam();
        jPanel2.setNextFocusableComponent(jtPesqParam);
        jPanel2.nextFocus();
        jtPesqParam.selectAll();
    }//GEN-LAST:event_jPanel2ComponentShown

    private void jtPesqParamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqParamKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            selectParam();  
        }  
    }//GEN-LAST:event_jtPesqParamKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       selectParam(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtAbrevKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAbrevKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             jtAbrev.setNextFocusableComponent(jtNome);
             jtAbrev.nextFocus();
        }  
    }//GEN-LAST:event_jtAbrevKeyPressed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             jtNome.setNextFocusableComponent(jtaDescri);
             jtNome.nextFocus();
        } 
    }//GEN-LAST:event_jtNomeKeyPressed

    public void selectParam(){
        objTM.setRowCount(0);
        System.out.println("codParametro select: "+SisPrinc.codParametro);
        switch(SisPrinc.codParametro){
            case 1:
                ResultSet marcaRs = mDao.selectMarca(jtPesqParam.getText());
                try{
                    while(marcaRs.next()){
                        String linha[] = {
                            marcaRs.getString("ID"),
                            marcaRs.getString("NOME"),
                            marcaRs.getString("DESCRI")
                        };
                        System.out.println(Arrays.toString(linha));
                           objTM.addRow(linha);
                        
                    }
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null, "Marca Não encontrada, "+ex);
                }
            break;
            case 2:
                ResultSet cateRs = cDao.selecionarCatego(jtPesqParam.getText());
                try{
                    while(cateRs.next()){
                        String linha[] = {
                            cateRs.getString("ID"),
                            cateRs.getString("NOME"),
                            cateRs.getString("DESCRI")
                        };
                        System.out.println(Arrays.toString(linha));
                           objTM.addRow(linha);
                        
                    }
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null, "Categoria Não encontrada, "+ex);
                }
            break;
            case 3:
                ResultSet umRs = umDao.selecionarUndMed(jtPesqParam.getText());
                try{
                    while(umRs.next()){
                        String linha[] = {
                            umRs.getString("ID"),
                            umRs.getString("ABREV"),
                            umRs.getString("NOME")
                        };
                        System.out.println(Arrays.toString(linha));
                           objTM.addRow(linha);
                        
                    }
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null, "Unidade de Medida Não encontrada, "+ex);
                }
            break;

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerirParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerirParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerirParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerirParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerirParametros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableParam;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbExcel;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtAbrev;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPesqParam;
    private javax.swing.JTextArea jtaDescri;
    // End of variables declaration//GEN-END:variables
}
