/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import ctrl.ClienteCtrl;
import ctrl.FamiliaCliCtrl;
import ctrl.DocumentJTextFIXACtrl;
import ctrl.DocumentJTextNumerosCtrl;
import ctrl.FornecedorCtrl;
import dao.ClienteDao;
import dao.ContasDao;
import dao.FamiliaCliDAO;
import dao.FornecedorDao;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import formularios.SisPrinc;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import sisvenda.SistemaVendas;

/**
 *
 * @author Adm
 */
public class GerirFornecedor extends javax.swing.JFrame {
    
    public boolean isEditFor = false;
    public FornecedorCtrl forCtrl = new FornecedorCtrl();
    public FornecedorDao forDao = new FornecedorDao();    
    
    public DefaultTableModel objTM;
    
    public GerirFornecedor() {
        initComponents();
        
        objTM = (DefaultTableModel) jTableFor.getModel();
        objTM.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtpFor = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtNomeFan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        edtRazaoSoci = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        edtCelFor = new javax.swing.JFormattedTextField();
        edtTelResiFor = new javax.swing.JFormattedTextField();
        edtEmailFor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        edtCnpjCpfFor = new javax.swing.JTextField();
        radioCpf = new javax.swing.JRadioButton();
        radioCnpj = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        edtCepFor = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        edtEnder = new javax.swing.JTextField();
        edtBairro = new javax.swing.JTextField();
        edtCidade = new javax.swing.JTextField();
        edtEstado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jlMenssager = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFor = new javax.swing.JTable();
        jbEditar = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jtPesqFor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbEncontrar = new javax.swing.JButton();
        jbDadosFull = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 600));
        setFocusTraversalPolicyProvider(true);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setOpacity(0.96F);
        setPreferredSize(new java.awt.Dimension(916, 560));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(0, 3));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel3.setNextFocusableComponent(edtNomeFan);
        jPanel3.setPreferredSize(new java.awt.Dimension(933, 550));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONTROLE DE FORNECEDORES");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(222, 35));
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel3.add(jLabel1, java.awt.BorderLayout.NORTH);

        jtpFor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtpFor.setPreferredSize(new java.awt.Dimension(912, 550));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(913, 492));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CONTATOS:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 155, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("DADOS PESSOAIS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 366, -1));

        edtNomeFan.setDocument(new DocumentJTextFIXACtrl());
        edtNomeFan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtNomeFan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtNomeFanFocusGained(evt);
            }
        });
        edtNomeFan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeFanActionPerformed(evt);
            }
        });
        edtNomeFan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtNomeFanKeyPressed(evt);
            }
        });
        jPanel1.add(edtNomeFan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Nome Fantazia: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Razão Social: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 96, -1));

        edtRazaoSoci.setDocument(new DocumentJTextFIXACtrl());
        edtRazaoSoci.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtRazaoSoci.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtRazaoSociFocusGained(evt);
            }
        });
        edtRazaoSoci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtRazaoSociActionPerformed(evt);
            }
        });
        edtRazaoSoci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtRazaoSociKeyPressed(evt);
            }
        });
        jPanel1.add(edtRazaoSoci, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("E-mail:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 240, 79, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Telefone Reside.:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 212, 104, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Celular:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 183, 104, -1));

        try {
            edtCelFor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtCelFor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtCelFor.setToolTipText("");
        edtCelFor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCelFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCelForActionPerformed(evt);
            }
        });
        edtCelFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCelForKeyPressed(evt);
            }
        });
        jPanel1.add(edtCelFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 178, 250, -1));

        try {
            edtTelResiFor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtTelResiFor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtTelResiFor.setToolTipText("");
        edtTelResiFor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtTelResiFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtTelResiForKeyPressed(evt);
            }
        });
        jPanel1.add(edtTelResiFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 207, 250, -1));

        edtEmailFor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtEmailFor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtEmailForFocusGained(evt);
            }
        });
        edtEmailFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmailForActionPerformed(evt);
            }
        });
        edtEmailFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtEmailForKeyPressed(evt);
            }
        });
        jPanel1.add(edtEmailFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 240, 250, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Identificação:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 103, 20));

        edtCnpjCpfFor.setDocument(new DocumentJTextNumerosCtrl());
        edtCnpjCpfFor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCnpjCpfFor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCnpjCpfForFocusGained(evt);
            }
        });
        edtCnpjCpfFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCnpjCpfForActionPerformed(evt);
            }
        });
        edtCnpjCpfFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCnpjCpfForKeyPressed(evt);
            }
        });
        jPanel1.add(edtCnpjCpfFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 149, -1));

        radioCpf.setText("CPF");
        radioCpf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioCpfItemStateChanged(evt);
            }
        });
        radioCpf.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioCpfStateChanged(evt);
            }
        });
        radioCpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioCpfMouseClicked(evt);
            }
        });
        radioCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCpfActionPerformed(evt);
            }
        });
        jPanel1.add(radioCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 100, 50, 22));

        radioCnpj.setText("CNPJ");
        radioCnpj.setPreferredSize(new java.awt.Dimension(15, 23));
        radioCnpj.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioCnpjItemStateChanged(evt);
            }
        });
        radioCnpj.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioCnpjStateChanged(evt);
            }
        });
        radioCnpj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioCnpjMouseClicked(evt);
            }
        });
        jPanel1.add(radioCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 100, 70, 22));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ENDEREÇO:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 297, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("CEP:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 104, 25));

        try {
            edtCepFor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtCepFor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtCepFor.setToolTipText("");
        edtCepFor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCepFor.setMargin(new java.awt.Insets(1, 1, 1, 1));
        edtCepFor.setMinimumSize(new java.awt.Dimension(58, 24));
        edtCepFor.setPreferredSize(new java.awt.Dimension(59, 25));
        edtCepFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCepForKeyPressed(evt);
            }
        });
        jPanel1.add(edtCepFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 250, 25));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Endereço:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 104, 25));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Bairro:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 104, 25));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Cidade:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 104, 25));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Estado:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 104, 25));

        edtEnder.setDocument(new DocumentJTextFIXACtrl());
        edtEnder.setMargin(new java.awt.Insets(1, 1, 1, 1));
        edtEnder.setMinimumSize(new java.awt.Dimension(58, 24));
        edtEnder.setPreferredSize(new java.awt.Dimension(59, 25));
        edtEnder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEnderActionPerformed(evt);
            }
        });
        edtEnder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtEnderKeyPressed(evt);
            }
        });
        jPanel1.add(edtEnder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 250, 25));

        edtBairro.setDocument(new DocumentJTextFIXACtrl());
        edtBairro.setMargin(new java.awt.Insets(1, 1, 1, 1));
        edtBairro.setMinimumSize(new java.awt.Dimension(58, 24));
        edtBairro.setPreferredSize(new java.awt.Dimension(59, 25));
        edtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtBairroActionPerformed(evt);
            }
        });
        edtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtBairroKeyPressed(evt);
            }
        });
        jPanel1.add(edtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 250, 25));

        edtCidade.setDocument(new DocumentJTextFIXACtrl());
        edtCidade.setMargin(new java.awt.Insets(1, 1, 1, 1));
        edtCidade.setMinimumSize(new java.awt.Dimension(58, 24));
        edtCidade.setPreferredSize(new java.awt.Dimension(59, 25));
        edtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCidadeActionPerformed(evt);
            }
        });
        edtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCidadeKeyPressed(evt);
            }
        });
        jPanel1.add(edtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 250, 25));

        edtEstado.setDocument(new DocumentJTextFIXACtrl());
        edtEstado.setMargin(new java.awt.Insets(1, 1, 1, 1));
        edtEstado.setMinimumSize(new java.awt.Dimension(58, 24));
        edtEstado.setPreferredSize(new java.awt.Dimension(59, 25));
        edtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEstadoActionPerformed(evt);
            }
        });
        edtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtEstadoKeyPressed(evt);
            }
        });
        jPanel1.add(edtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 250, 25));

        txtObs.setColumns(20);
        txtObs.setDocument(new DocumentJTextFIXACtrl());
        txtObs.setRows(5);
        txtObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtObsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtObs);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 460, 220));

        jlMenssager.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jlMenssager.setForeground(new java.awt.Color(255, 51, 51));
        jlMenssager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMenssager.setText("---<Cadastrando FORNECEDOR>---");
        jlMenssager.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlMenssager.setNextFocusableComponent(edtNomeFan);
        jPanel1.add(jlMenssager, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 490, 50));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("ANOTAÇÕES");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jbSalvar.setBackground(new java.awt.Color(32, 32, 32));
        jbSalvar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jbSalvar.setForeground(new java.awt.Color(239, 239, 239));
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 120, 57));

        jbCancelar.setBackground(new java.awt.Color(32, 32, 32));
        jbCancelar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jbCancelar.setForeground(new java.awt.Color(239, 239, 239));
        jbCancelar.setText("Cancelar");
        jbCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbCancelarMousePressed(evt);
            }
        });
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 120, 57));

        jtpFor.addTab("CADASTRAR", jPanel1);

        jPanel5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel5ComponentShown(evt);
            }
        });

        jTableFor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOME FANTAZIA", "CPF/CNPJ", "CELULAR", "TELEFONE", "EMAIL", "OBSERVAÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableFor);
        if (jTableFor.getColumnModel().getColumnCount() > 0) {
            jTableFor.getColumnModel().getColumn(0).setMinWidth(70);
            jTableFor.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTableFor.getColumnModel().getColumn(0).setMaxWidth(70);
            jTableFor.getColumnModel().getColumn(1).setMinWidth(145);
            jTableFor.getColumnModel().getColumn(1).setPreferredWidth(145);
            jTableFor.getColumnModel().getColumn(1).setMaxWidth(145);
            jTableFor.getColumnModel().getColumn(2).setMinWidth(85);
            jTableFor.getColumnModel().getColumn(2).setPreferredWidth(85);
            jTableFor.getColumnModel().getColumn(2).setMaxWidth(85);
            jTableFor.getColumnModel().getColumn(3).setMinWidth(100);
            jTableFor.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableFor.getColumnModel().getColumn(3).setMaxWidth(100);
            jTableFor.getColumnModel().getColumn(4).setMinWidth(100);
            jTableFor.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableFor.getColumnModel().getColumn(4).setMaxWidth(100);
            jTableFor.getColumnModel().getColumn(5).setMinWidth(140);
            jTableFor.getColumnModel().getColumn(5).setPreferredWidth(140);
            jTableFor.getColumnModel().getColumn(5).setMaxWidth(140);
        }

        jbEditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jtPesqFor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtPesqFor.setToolTipText("Abreviatura do nome");
        jtPesqFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesqForActionPerformed(evt);
            }
        });
        jtPesqFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPesqForKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Pesquisar:");

        jbEncontrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbEncontrar.setText("ENCONTRAR");
        jbEncontrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEncontrarActionPerformed(evt);
            }
        });

        jbDadosFull.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbDadosFull.setText("Dados completos");
        jbDadosFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDadosFullActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jbDadosFull)
                        .addGap(64, 64, 64)
                        .addComponent(jbCancel))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtPesqFor, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbEncontrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPesqFor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbEncontrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jbDadosFull, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jbCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtpFor.addTab("CONSULTAR", jPanel5);

        jPanel3.add(jtpFor, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleParent(edtNomeFan);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        
               forCtrl.setBairro(edtBairro.getText());
               forCtrl.setCelular(edtCelFor.getText());
               
                String[] cep = edtCepFor.getText().split("-");
                if(edtCepFor.getText().equals("") || edtCepFor.getText().equals("-"))forCtrl.setCep(0);
                else forCtrl.setCep(Integer.parseInt(cep[0]+cep[1]));
               
                forCtrl.setCidade(edtCidade.getText());
               forCtrl.setCpf_cnpj(Integer.parseInt(edtCnpjCpfFor.getText()));
               if(radioCnpj.isSelected()) forCtrl.setCpf_or_cnpj("CNPJ");
               if(radioCpf.isSelected()) forCtrl.setCpf_or_cnpj("CPF");
               forCtrl.setEmail(edtEmailFor.getText());
               forCtrl.setEnder(edtEnder.getText());
               forCtrl.setEstado(edtEstado.getText());
               forCtrl.setNome_fantazia(edtNomeFan.getText());
               forCtrl.setObs(txtObs.getText());
               forCtrl.setRazao_social(edtRazaoSoci.getText());
               forCtrl.setTelefone(edtTelResiFor.getText());
        //Salvar
        if(!isEditFor){
            if(forDao.selectCodForneceID(edtCnpjCpfFor.getText()) < 1){

                forDao.inserir(forCtrl);
                
                edtNomeFan.setText("");
                edtRazaoSoci.setText("");
                edtCnpjCpfFor.setText("");
                edtCelFor.setText("");
                edtTelResiFor.setText("");
                edtEmailFor.setText("");
                edtCepFor.setText("");
                edtEnder.setText("");
                edtBairro.setText("");
                edtCidade.setText("");
                edtEstado.setText("");
                txtObs.setText("");
                
                jbSalvar.setNextFocusableComponent(edtNomeFan);
                jbSalvar.nextFocus();
                
            }else JOptionPane.showMessageDialog(null, "Fornecedor já existente");
         //editar
        }else{
            if(forDao.selectCodForneceID(edtCnpjCpfFor.getText()) < 1){
                forDao.alterar(forCtrl);
                
                edtNomeFan.setText("");
                edtRazaoSoci.setText("");
                edtCnpjCpfFor.setText("");
                edtCelFor.setText("");
                edtTelResiFor.setText("");
                edtEmailFor.setText("");
                edtCepFor.setText("");
                edtEnder.setText("");
                edtBairro.setText("");
                edtCidade.setText("");
                edtEstado.setText("");
                txtObs.setText("");
                
                jbSalvar.setNextFocusableComponent(edtNomeFan);
                jbSalvar.nextFocus();
             
                isEditFor = false;
            }else JOptionPane.showMessageDialog(null, "Fornecedor já existente");
        }
        
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void edtNomeFanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeFanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeFanActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void edtNomeFanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtNomeFanKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           
              jlMenssager.setText("---<Cadastrando Fornecedor>---"); 
              edtNomeFan.setNextFocusableComponent(edtRazaoSoci);
              edtNomeFan.nextFocus();
           
       }
    }//GEN-LAST:event_edtNomeFanKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jbCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarMousePressed

    private void edtNomeFanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtNomeFanFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeFanFocusGained

    private void edtCelForKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCelForKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            edtCelFor.setNextFocusableComponent(edtTelResiFor);
            edtCelFor.nextFocus();

        }
    }//GEN-LAST:event_edtCelForKeyPressed

    private void edtTelResiForKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtTelResiForKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            edtTelResiFor.setNextFocusableComponent(edtEmailFor);
            edtTelResiFor.nextFocus();

        }
    }//GEN-LAST:event_edtTelResiForKeyPressed

    private void edtEmailForFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtEmailForFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmailForFocusGained

    private void edtEmailForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmailForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmailForActionPerformed

    private void edtEmailForKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtEmailForKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            edtEmailFor.setNextFocusableComponent(edtCepFor);
            edtEmailFor.nextFocus();

        }
    }//GEN-LAST:event_edtEmailForKeyPressed

    private void edtCnpjCpfForFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCnpjCpfForFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCnpjCpfForFocusGained

    private void edtCnpjCpfForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCnpjCpfForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCnpjCpfForActionPerformed

    private void edtCnpjCpfForKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCnpjCpfForKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(forDao.selectCodForneceID(edtCnpjCpfFor.getText()) > 1){
                jlMenssager.setText("CPF já cadastrado"); 
                edtRazaoSoci.nextFocus();
                edtCnpjCpfFor.selectAll();
            }else{
                edtCnpjCpfFor.setNextFocusableComponent(edtCelFor);
                edtCnpjCpfFor.nextFocus();
            }
        }
    }//GEN-LAST:event_edtCnpjCpfForKeyPressed

    private void edtCepForKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCepForKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            edtCepFor.setNextFocusableComponent(edtEnder);
            edtCepFor.nextFocus();
        }
    }//GEN-LAST:event_edtCepForKeyPressed

    private void edtEnderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEnderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEnderActionPerformed

    private void edtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtBairroActionPerformed

    private void edtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCidadeActionPerformed

    private void edtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEstadoActionPerformed

    private void edtCelForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCelForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCelForActionPerformed

    private void edtEnderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtEnderKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            edtEnder.setNextFocusableComponent(edtBairro);
            edtEnder.nextFocus();
        }
    }//GEN-LAST:event_edtEnderKeyPressed

    private void edtBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtBairroKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            edtBairro.setNextFocusableComponent(edtCidade);
            edtBairro.nextFocus();
        }
    }//GEN-LAST:event_edtBairroKeyPressed

    private void edtCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCidadeKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            edtCidade.setNextFocusableComponent(edtEstado);
            edtCidade.nextFocus();
        }
    }//GEN-LAST:event_edtCidadeKeyPressed

    private void edtEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtEstadoKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            edtEstado.setNextFocusableComponent(txtObs);
            edtEstado.nextFocus();
        }
    }//GEN-LAST:event_edtEstadoKeyPressed

    private void radioCnpjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioCnpjMouseClicked

    }//GEN-LAST:event_radioCnpjMouseClicked

    private void radioCpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioCpfMouseClicked

    }//GEN-LAST:event_radioCpfMouseClicked

    private void radioCnpjStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioCnpjStateChanged
  
    }//GEN-LAST:event_radioCnpjStateChanged

    private void radioCpfStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioCpfStateChanged
 
    }//GEN-LAST:event_radioCpfStateChanged

    private void radioCnpjItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioCnpjItemStateChanged
        radioCpf.setSelected(false);
    }//GEN-LAST:event_radioCnpjItemStateChanged

    private void radioCpfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioCpfItemStateChanged
         radioCnpj.setSelected(false);
    }//GEN-LAST:event_radioCpfItemStateChanged

    private void txtObsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           
        }
    }//GEN-LAST:event_txtObsKeyPressed

    private void edtRazaoSociKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtRazaoSociKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            edtRazaoSoci.setNextFocusableComponent(edtCnpjCpfFor);
            edtRazaoSoci.nextFocus();
        }
    }//GEN-LAST:event_edtRazaoSociKeyPressed

    private void edtRazaoSociActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtRazaoSociActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtRazaoSociActionPerformed

    private void edtRazaoSociFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtRazaoSociFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_edtRazaoSociFocusGained

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        if(jTableFor.getSelectedRow() != -1){
            ResultSet rsFor = forDao.selectFornece(objTM.getValueAt(jTableFor.getSelectedRow(), 0).toString());
            
            try {
                rsFor.first();
                    forCtrl.setID(Integer.parseInt(rsFor.getString("ID")));
                    forCtrl.setCodigo(rsFor.getString("CODIGO"));
                    forCtrl.setCep(Integer.parseInt(rsFor.getString("CEP")));
                    forCtrl.setBairro(rsFor.getString("BAIRRO"));
                    forCtrl.setCelular(rsFor.getString("CELULAR"));
                    forCtrl.setCidade(rsFor.getString("CIDADE"));
                    forCtrl.setCpf_cnpj(Integer.parseInt(rsFor.getString("CPF_CNPJ")));
                    if(rsFor.getString("CPF_OR_CNPJ").equals("CPF")) forCtrl.setCpf_or_cnpj("CPF");
                    if(rsFor.getString("CPF_OR_CNPJ").equals("CNPJ")) forCtrl.setCpf_or_cnpj("CNPJ");
                    forCtrl.setEmail(rsFor.getString("EMAIL"));
                    forCtrl.setEnder(rsFor.getString("ENDER"));
                    forCtrl.setEstado(rsFor.getString("ESTADO"));
                    forCtrl.setNome_fantazia(rsFor.getString("NOME_FANTAZIA"));
                    forCtrl.setObs(rsFor.getString("OBS"));
                    forCtrl.setRazao_social(rsFor.getString("RAZAO_SOCIAL"));
                    forCtrl.setTelefone(rsFor.getString("TELEFONE"));
               
                    edtNomeFan.setText(forCtrl.getNome_fantazia());
                    edtRazaoSoci.setText(forCtrl.getRazao_social());
                    edtCnpjCpfFor.setText(""+forCtrl.getCpf_cnpj());
                    if(forCtrl.getCpf_or_cnpj().equals("CPF")) radioCpf.setSelected(true);
                    if(forCtrl.getCpf_or_cnpj().equals("CNPJ")) radioCnpj.setSelected(true);
                    edtCelFor.setText(forCtrl.getCelular());
                    edtTelResiFor.setText(forCtrl.getTelefone());
                    edtEmailFor.setText(forCtrl.getEmail());
                    edtCepFor.setText(""+forCtrl.getCep());
                    edtEnder.setText(forCtrl.getEnder());
                    edtBairro.setText(forCtrl.getBairro());
                    edtCidade.setText(forCtrl.getCidade());
                    edtEstado.setText(forCtrl.getEstado());
                    txtObs.setText(forCtrl.getObs());
                
                    jtpFor.setSelectedIndex(0);
                    
                    jbEditar.setNextFocusableComponent(edtNomeFan);
                    jbEditar.nextFocus();
                    edtNomeFan.selectAll();
                    
                    isEditFor = true;
                
            } catch (SQLException ex) {
                Logger.getLogger(GerirFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Erro na consulda de Fornecedores, "+ex);
            }
            
        }
           
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jtPesqForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesqForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPesqForActionPerformed

    private void jtPesqForKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqForKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            selectForce();
        }
    }//GEN-LAST:event_jtPesqForKeyPressed

    private void jbEncontrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEncontrarActionPerformed
        selectForce();
    }//GEN-LAST:event_jbEncontrarActionPerformed

    private void jbDadosFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDadosFullActionPerformed
        
        if(jTableFor.getSelectedRow() != -1){
            ResultSet rsFor = forDao.selectFornece(objTM.getValueAt(jTableFor.getSelectedRow(), 0).toString());
            
            try {
                rsFor.first();
                    forCtrl.setID(Integer.parseInt(rsFor.getString("ID")));
                    forCtrl.setCodigo(rsFor.getString("CODIGO"));
                    forCtrl.setCep(Integer.parseInt(rsFor.getString("CEP")));
                    forCtrl.setBairro(rsFor.getString("BAIRRO"));
                    forCtrl.setCelular(rsFor.getString("CELULAR"));
                    forCtrl.setCidade(rsFor.getString("CIDADE"));
                    forCtrl.setCpf_cnpj(Integer.parseInt(rsFor.getString("CPF_CNPJ")));
                    if(rsFor.getString("CPF_OR_CNPJ").equals("CPF")) radioCpf.isSelected();
                    if(rsFor.getString("CPF_OR_CNPJ").equals("CNPJ")) radioCnpj.isSelected();
                    forCtrl.setEmail(rsFor.getString("EMAIL"));
                    forCtrl.setEnder(rsFor.getString("ENDER"));
                    forCtrl.setEstado(rsFor.getString("ESTADO"));
                    forCtrl.setNome_fantazia(rsFor.getString("NOME_FANTAZIA"));
                    forCtrl.setObs(rsFor.getString("OBS"));
                    forCtrl.setRazao_social(rsFor.getString("RAZAO_SOCIAL"));
                    forCtrl.setTelefone(rsFor.getString("TELEFONE"));
               
                    edtNomeFan.setText(forCtrl.getNome_fantazia());
                    edtRazaoSoci.setText(forCtrl.getRazao_social());
                    edtCnpjCpfFor.setText(""+forCtrl.getCpf_cnpj());
                    if(forCtrl.getCpf_or_cnpj().equals("CPF")) radioCpf.isSelected();
                    if(forCtrl.getCpf_or_cnpj().equals("CNPJ")) radioCnpj.isSelected();
                    edtCelFor.setText(forCtrl.getCelular());
                    edtTelResiFor.setText(forCtrl.getTelefone());
                    edtEmailFor.setText(forCtrl.getEmail());
                    edtCepFor.setText(""+forCtrl.getCep());
                    edtEnder.setText(forCtrl.getEnder());
                    edtBairro.setText(forCtrl.getBairro());
                    edtCidade.setText(forCtrl.getCidade());
                    edtEstado.setText(forCtrl.getEstado());
                    txtObs.setText(forCtrl.getObs());
                
                    jtpFor.setSelectedIndex(0);
                    
                    jbSalvar.setEnabled(false);
                
            } catch (SQLException ex) {
                Logger.getLogger(GerirFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Erro na consulda de Fornecedores, "+ex);
            }
            
        }
    }//GEN-LAST:event_jbDadosFullActionPerformed

    private void jPanel5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel5ComponentShown
        selectForce();
    }//GEN-LAST:event_jPanel5ComponentShown

    private void radioCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCpfActionPerformed

    public void selectForce(){
        objTM.setRowCount(0);
                ResultSet forRs = forDao.selectFornece(jtPesqFor.getText());
                try{
                    while(forRs.next()){
                        String linha[] = {
                            forRs.getString("CODIGO"),
                            forRs.getString("NOME_FANTAZIA"),
                            forRs.getString("CPF_CNPJ"),
                            forRs.getString("CELULAR"),
                            forRs.getString("TELEFONE"),
                            forRs.getString("EMAIL"),
                            forRs.getString("OBS")
                        };
                        System.out.println(Arrays.toString(linha));
                           objTM.addRow(linha);
                    }      
                    
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null, "FORNECEDOR Não encontrada, "+ex);
                }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edtBairro;
    private javax.swing.JFormattedTextField edtCelFor;
    private javax.swing.JFormattedTextField edtCepFor;
    private javax.swing.JTextField edtCidade;
    private javax.swing.JTextField edtCnpjCpfFor;
    private javax.swing.JTextField edtEmailFor;
    private javax.swing.JTextField edtEnder;
    private javax.swing.JTextField edtEstado;
    private javax.swing.JTextField edtNomeFan;
    private javax.swing.JTextField edtRazaoSoci;
    private javax.swing.JFormattedTextField edtTelResiFor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFor;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbDadosFull;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbEncontrar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlMenssager;
    private javax.swing.JTextField jtPesqFor;
    private javax.swing.JTabbedPane jtpFor;
    private javax.swing.JRadioButton radioCnpj;
    private javax.swing.JRadioButton radioCpf;
    private javax.swing.JTextArea txtObs;
    // End of variables declaration//GEN-END:variables
}
