/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import ctrl.ContasCtrl;
import dao.ClienteDao;
import dao.CompraDao;
import dao.ContasDao;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas
 */
class PagCompra extends javax.swing.JFrame {
    
    public int idCli;
    public boolean hasConta = false;
    public String dataOpen;
    /**
     * Creates new form PagCompra
     */
    public PagCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jNomeClie = new javax.swing.JTextField();
        jcombNome = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlValorTotal = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        lStatus = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jfData = new javax.swing.JFormattedTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jlValconta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADICIONANDO NA CONTYA");
        setLocation(new java.awt.Point(450, 250));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionando a Conta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Digite o NOME ou CÓDIGO do Cliente:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jNomeClie.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jNomeClie.setBorder(null);
        jNomeClie.setPreferredSize(new java.awt.Dimension(100, 23));
        jNomeClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeClieActionPerformed(evt);
            }
        });
        jNomeClie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNomeClieKeyPressed(evt);
            }
        });
        jPanel2.add(jNomeClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 132, 340, 35));

        jcombNome.setEditable(true);
        jcombNome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcombNome.setNextFocusableComponent(jNomeClie);
        jcombNome.setPreferredSize(new java.awt.Dimension(245, 35));
        jcombNome.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jcombNomeComponentShown(evt);
            }
        });
        jcombNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombNomeActionPerformed(evt);
            }
        });
        jcombNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcombNomeKeyReleased(evt);
            }
        });
        jPanel2.add(jcombNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 370, 40));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Valor Total:");
        jPanel4.add(jLabel2);

        jlValorTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlValorTotal.setText("00,00");
        jPanel4.add(jlValorTotal);

        jSeparator2.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator2.setForeground(new java.awt.Color(240, 240, 240));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setEnabled(false);
        jSeparator2.setMinimumSize(new java.awt.Dimension(25, 10));
        jSeparator2.setPreferredSize(new java.awt.Dimension(10, 30));
        jPanel4.add(jSeparator2);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMinimumSize(new java.awt.Dimension(25, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 30));
        jPanel4.add(jSeparator1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Status:");
        jPanel4.add(jLabel4);

        lStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lStatus.setText("Status");
        jPanel4.add(lStatus);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 460, -1));

        jToggleButton1.setBackground(new java.awt.Color(43, 43, 43));
        jToggleButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(223, 223, 223));
        jToggleButton1.setText("Pesquisar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 90, 40));

        jButton1.setBackground(new java.awt.Color(43, 43, 43));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(223, 223, 223));
        jButton1.setText("Adicionar a Conta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 210, 60));

        jButton2.setBackground(new java.awt.Color(43, 43, 43));
        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(223, 223, 223));
        jButton2.setText("Cancelar Processo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 210, 60));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        jPanel5.setPreferredSize(new java.awt.Dimension(460, 45));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Data Pagamento:");

        try {
            jfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfData.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jfData.setPreferredSize(new java.awt.Dimension(172, 22));
        jfData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfDataActionPerformed(evt);
            }
        });
        jfData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jfDataKeyPressed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setMinimumSize(new java.awt.Dimension(25, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(10, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Devendo:");

        jlValconta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlValconta.setText("00,00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jfData, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlValconta, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlValconta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 470, -1));

        getContentPane().add(jPanel2, "card3");

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNomeClieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNomeClieKeyPressed
        ClienteDao objDao = new ClienteDao();
        ContasDao objCotaDao = new ContasDao();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER && !jNomeClie.getText().equals("")){
            ResultSet objRs = objDao.selecionarUser(jNomeClie.getText());
            jcombNome.removeAllItems();
            try {
                while(objRs.next()){jcombNome.addItem(objRs.getString("nomeCli"));}
                while(objRs.previous()){}

                objRs.next();
                idCli = objRs.getInt("id");
            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(null, "Cliente não encontrado "+ex);
            }
            //verificando conta de cliente
            hasConta = objCotaDao.checkContaCli(idCli);
            if(hasConta){
                //JOptionPane.showMessageDialog(null, "asdfasdasdasd ");
                ResultSet objRsConta = objCotaDao.selectConta(idCli);
                try {
                    objRs.first();
                    dataOpen = objRsConta.getString("data_open");
                    jfData.setText(objRsConta.getString("data_pag"));
                    jlValconta.setText(objRsConta.getString("valor"));
                    
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "erro ao fazer cunsulta de COntas "+ex);
                }
                jNomeClie.setNextFocusableComponent(jfData);
                jNomeClie.nextFocus();
                jfData.selectAll();
                
            }else{
                //JOptionPane.showMessageDialog(null, "--------- ");
                jNomeClie.setNextFocusableComponent(jfData);
                jNomeClie.nextFocus();
                jfData.selectAll();
                jlValconta.setText("00,00");
            }
            jNomeClie.setText(jcombNome.getItemAt(0));
            lStatus.setText(objDao.selecionarStatusUser(String.valueOf(idCli)));
            jcombNome.setNextFocusableComponent(jNomeClie);
            jcombNome.nextFocus();

            if(jcombNome.getItemCount()<1){
                if(JOptionPane.showConfirmDialog(null, "Deseja Cadastra-lo?", "CLIENTE NÃO ENCONTRADO", 0)==0){
                    GerirCliente cadCli = new GerirCliente();
                    cadCli.show();
                }
            }
        }
    }//GEN-LAST:event_jNomeClieKeyPressed

    private void jcombNomeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jcombNomeComponentShown
        ClienteDao objDao = new ClienteDao();

        ResultSet objRs = objDao.selecionar();
        jcombNome.removeAllItems();
        try {
            while(objRs.next()){jcombNome.addItem(objRs.getString("nomeCli"));}

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro ao fazer cunsulta de Clientes test");
        }
    }//GEN-LAST:event_jcombNomeComponentShown

    private void jcombNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombNomeActionPerformed

        
        jNomeClie.setText(jcombNome.getItemAt(jcombNome.getSelectedIndex()));

        jcombNome.setNextFocusableComponent(jNomeClie);
        jcombNome.nextFocus();
    }//GEN-LAST:event_jcombNomeActionPerformed

    private void jcombNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcombNomeKeyReleased

    }//GEN-LAST:event_jcombNomeKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CompraDao objDao = new CompraDao();
        ClienteDao objCliDao = new ClienteDao();
        ContasDao objContaDao = new ContasDao();
        ContasCtrl objContaCtrl = new ContasCtrl();
        
        String valTotal = jlValorTotal.getText();
        String data, hora;
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
        data = (formato.format(dataSistema));
        Calendar now = Calendar.getInstance();
        hora = (String.format("%1$tH:%1$tM:%1tS", now));
        valTotal = valTotal.replace(",", ".");

        objDao.alterar(SisPrinc.codComp, idCli, Double.valueOf(valTotal), data,  hora, "NA CONTA");
        objCliDao.alterarSituation(idCli, jNomeClie.getText(), "DEVENDO");
        
        if(hasConta){
            objContaDao.alterar(idCli, Double.valueOf(valTotal)+objContaDao.selectValor(idCli),
                                    jfData.getText().substring(6,10)+
                                    jfData.getText().substring(2,6)+
                                    jfData.getText().substring(0,2),dataOpen, "DEVENDO");
        }else{
            objContaCtrl.setCod_cli(idCli);
            objContaCtrl.setData_pag(jfData.getText().substring(6,10)+
                                     jfData.getText().substring(2,6)+
                                     jfData.getText().substring(0,2));

            objContaCtrl.setValor(Double.valueOf(valTotal));
            objContaCtrl.setStatus("DEVENDO");
            objContaDao.inserir(objContaCtrl);
        }
            
            
            JOptionPane.showMessageDialog(null, "VENDA REALIZADA COM SUCESSO!!!");
        SisPrinc.clearTablePro = true;
        jlValorTotal.setText("00,00");
        lStatus.setText("STATUS");
        jNomeClie.setText("");
        jcombNome.removeAllItems();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        ClienteDao objDao = new ClienteDao();

            ResultSet objRs = objDao.selecionarUser(jNomeClie.getText());
            jcombNome.removeAllItems();
            try {
                while(objRs.next()){jcombNome.addItem(objRs.getString("nomeCli"));}

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "erro ao fazer cunsulta de clientes por Nome");
            }
            jNomeClie.setText(jcombNome.getItemAt(0));
            jcombNome.setNextFocusableComponent(jNomeClie);
            jcombNome.nextFocus();

            if(jcombNome.getItemCount()<1) JOptionPane.showMessageDialog(null, "PRODUTO NÃO ENCONTRADO");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jlValorTotal.setText(String.valueOf(SisPrinc.valTotalCompra).replace(".", ","));
        jcombNome.nextFocus();
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void jNomeClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeClieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeClieActionPerformed

    private void jfDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfDataActionPerformed

    private void jfDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jfDataKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        CompraDao objDao = new CompraDao();
        ClienteDao objCliDao = new ClienteDao();
        ContasDao objContaDao = new ContasDao();
        ContasCtrl objContaCtrl = new ContasCtrl();
        
        String valTotal = jlValorTotal.getText();
        String data, hora;
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
        data = (formato.format(dataSistema));
        Calendar now = Calendar.getInstance();
        hora = (String.format("%1$tH:%1$tM:%1tS", now));
        valTotal = valTotal.replace(",", ".");

        objDao.alterar(SisPrinc.codComp, idCli, Double.valueOf(valTotal), data,  hora, "NA CONTA");
        objCliDao.alterarSituation(idCli, jNomeClie.getText(), "DEVENDO");
        
        if(hasConta){
            objContaDao.alterar(idCli, Double.valueOf(valTotal)+objContaDao.selectValor(idCli),
                                    jfData.getText().substring(6,10)+
                                    jfData.getText().substring(2,6)+
                                    jfData.getText().substring(0,2),dataOpen, "DEVENDO");
        }else{
            objContaCtrl.setCod_cli(idCli);
            objContaCtrl.setData_pag(jfData.getText().substring(6,10)+
                                     jfData.getText().substring(2,6)+
                                     jfData.getText().substring(0,2));
             
            objContaCtrl.setValor(Double.valueOf(valTotal));
            objContaCtrl.setStatus("DEVENDO");
            objContaDao.inserir(objContaCtrl);
        }
            
            
            JOptionPane.showMessageDialog(null, "VENDA REALIZADA COM SUCESSO!!!");
        SisPrinc.clearTablePro = true;
        jlValorTotal.setText("00,00");
        lStatus.setText("STATUS");
        jNomeClie.setText("");
        jcombNome.removeAllItems();
        dispose();
      }
    }//GEN-LAST:event_jfDataKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jNomeClie;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> jcombNome;
    private javax.swing.JFormattedTextField jfData;
    private javax.swing.JLabel jlValconta;
    private javax.swing.JLabel jlValorTotal;
    private javax.swing.JLabel lStatus;
    // End of variables declaration//GEN-END:variables
}
