/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import ctrl.ContasCtrl;
import dao.ClienteDao;
import dao.CompraDao;
import dao.ContasDao;
import dao.RelatorioDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Douglas
 */
public class PagConta extends javax.swing.JFrame {
    
    public String dataOP;
    public int codConta;
    /**
     * Creates new form PagConta
     */
    public PagConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jlNomeCli = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jlValorDev = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCompCli = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PAGAMENTO DE CONTA");
        setLocation(new java.awt.Point(430, 200));
        setUndecorated(true);
        setOpacity(0.95F);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagando Conta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 5));

        jSeparator2.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator2.setForeground(new java.awt.Color(240, 240, 240));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setEnabled(false);
        jSeparator2.setMinimumSize(new java.awt.Dimension(25, 10));
        jSeparator2.setPreferredSize(new java.awt.Dimension(10, 30));
        jPanel4.add(jSeparator2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cliente:");
        jPanel4.add(jLabel4);

        jlNomeCli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlNomeCli.setText("Nome");
        jlNomeCli.setPreferredSize(new java.awt.Dimension(250, 22));
        jPanel4.add(jlNomeCli);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMinimumSize(new java.awt.Dimension(25, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 30));
        jPanel4.add(jSeparator1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Devendo:");
        jPanel4.add(jLabel2);

        jlValorDev.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlValorDev.setText("00,00");
        jPanel4.add(jlValorDev);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 540, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("PAGAR CONTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 210, 60));

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 210, 60));

        jtCompCli.setAutoCreateRowSorter(true);
        jtCompCli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtCompCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "DATA", "HORA", "COD.", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCompCli.setRowHeight(23);
        jtCompCli.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtCompCli);
        jtCompCli.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtCompCli.getColumnModel().getColumnCount() > 0) {
            jtCompCli.getColumnModel().getColumn(0).setMinWidth(130);
            jtCompCli.getColumnModel().getColumn(0).setMaxWidth(130);
            jtCompCli.getColumnModel().getColumn(1).setMinWidth(130);
            jtCompCli.getColumnModel().getColumn(1).setMaxWidth(130);
            jtCompCli.getColumnModel().getColumn(2).setMinWidth(80);
            jtCompCli.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 540, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CompraDao objDao = new CompraDao();
        ContasDao objContaDao = new ContasDao();
        ClienteDao objDaoCli = new  ClienteDao();
        DefaultTableModel objTableM = (DefaultTableModel) jtCompCli.getModel();

        
        objContaDao.deletar(codConta, SisPrinc.codCli);
        objDaoCli.alterarSituation(SisPrinc.codCli, SisPrinc.nomeCli, "NORMAL");
        
        for(int x=0;x<objTableM.getRowCount();x++){
            objDao.alterar(Integer.parseInt(objTableM.getValueAt(x, 2).toString()), SisPrinc.codCli, 
                   Double.valueOf(objTableM.getValueAt(x, 3).toString()), objTableM.getValueAt(x, 0).toString().substring(6,10)+
                                                                          objTableM.getValueAt(x, 0).toString().substring(2,6)+
                                                                          objTableM.getValueAt(x, 0).toString().substring(0,2),
                   objTableM.getValueAt(x, 1).toString(), "CONTA PAGA");
        }
        dispose();
        JOptionPane.showMessageDialog(null, "CONTA PAGA COM SUCESSO!!!");
        objTableM.setRowCount(0);
        jlValorDev.setText("00,00");
        dataOP = null;
        jlNomeCli.setText("Nome");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel objTableM = (DefaultTableModel) jtCompCli.getModel();
        objTableM.setRowCount(0);
        jlValorDev.setText("00,00");
        dataOP = null;
        jlNomeCli.setText("Nome");
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
      if(jlNomeCli.getText().equals("Nome")){
        ContasDao objContaDao = new ContasDao();
        RelatorioDAO objDAORel = new RelatorioDAO();
        DefaultTableModel objTableM = (DefaultTableModel) jtCompCli.getModel();
        ResultSet objRs = objContaDao.selectConta(SisPrinc.codCli);
        
            try {
                objRs.first();
                    dataOP = objRs.getString("data_open");
                    codConta = Integer.parseInt(objRs.getString("cod_conta"));
                    jlValorDev.setText(objRs.getString("valor"));
                

            } catch (SQLException ex) { JOptionPane.showMessageDialog(null, "erro ao fazer cunsulta de Conta "+ex);}
            jlNomeCli.setText(SisPrinc.nomeCli);
            
            ResultSet objRsVend = objDAORel.consultVendaCLi(dataOP,SisPrinc.codCli);
                try {
                   objTableM.setRowCount(0);
                   while(objRsVend.next()){
                       String linha[] = {
                            objRsVend.getString("dataCompra").substring(8,10)+"/"+
                            objRsVend.getString("dataCompra").substring(5,7)+"/"+
                            objRsVend.getString("dataCompra").substring(0,4),
                           
                            objRsVend.getString("horaCompra"),
                            objRsVend.getString("codigo"),
                            objRsVend.getString("valorTotal")

                       };
                       objTableM.addRow(linha);
                }} catch (SQLException ex) {
                       JOptionPane.showMessageDialog(null, "erro ao fazer cunsulta de Venda Detalhada"+ex);
                }
      }
            
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlNomeCli;
    private javax.swing.JLabel jlValorDev;
    private javax.swing.JTable jtCompCli;
    // End of variables declaration//GEN-END:variables
}
